variables:
- group: azure-credentials

stages:

- stage: test
  jobs:
  - job: test

    pool:
      name: Hosted Ubuntu 1604

    steps:

    - script: |
        terraform init -backend=false terraform-config/
      displayName: 'Terraform Init'

    - script: |
        terraform validate
      displayName: 'Terraform Validate'

    - script: |
        terraform plan --out plan.out terraform-config/
      env:
        ARM_CLIENT_ID: $(internal-client-id)
        ARM_CLIENT_SECRET: $(internal-secret)
        ARM_TENANT_ID: $(internal-tenant-id)
        ARM_SUBSCRIPTION_ID: $(internal-subscription-id)
      displayName: 'Terraform Plan'

    - script: |
        terraform apply plan.out
      displayName: 'Terraform Apply'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'ca-nepeters-demo-test (3762d87c-ddb8-425f-b2fc-29e5e859edaf)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az container show --resource-group hello-world --name HelloWorld --query ipAddress.ip -o tsv'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'ca-nepeters-demo-test (3762d87c-ddb8-425f-b2fc-29e5e859edaf)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          IP=$(az container show --resource-group hello-world --name HelloWorld --query ipAddress.ip -o tsv)
          
          echo "##vso[task.setvariable variable IP;]$IP"

    - script: |
        echo $IP
      displayName: 'Echo IP'


# - script: |
#    export GOPATH=$(Build.Repository.LocalPath)
#    cd ../test/
#    pwd
#    ls
#    cd test
#    pwd
#    ls
#    go get github.com/gruntwork-io/terratest/modules/terraform
#    go test | tee test_output.log
#    terratest_log_parser -testlog test_output.log -outputdir test_output
#   displayName: 'Run Terraform Tests'
#   env:
#    # ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
#    ARM_CLIENT_ID: $(internal-client-id)
#    ARM_CLIENT_SECRET: $(internal-secret)
#    ARM_TENANT_ID: $(internal-tenant-id)
#    ARM_SUBSCRIPTION_ID: $(internal-subscription-id)